FROM microsoft/dotnet:2.2-sdk

WORKDIR /home/app

COPY ./*.sln ./
COPY ./*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./${file%.*}/ && mv $file ./${file%.*}/; done

RUN dotnet restore

COPY . .

WORKDIR /home/app/

ENTRYPOINT ["dotnet", "test", "--verbosity=normal"]